title: Nghi Huynh # your name (or website title) here
logo: "/images/logo-nghi.png" # your photo (or logo) here

description:
  <p align="center">
  <a href="pdf/Nghi_Huynh_cv2022_np.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nghi-huynh-2b9700158/">LinkedIn</a> |
  <a href="https://github.com/nghi-huynh">GitHub</a>
  </p>
  
  <p align="justify">
  Hello, I'm Nghi. I'm a McGill graduate with a major in Computer Science and Biology and a minor in Mathematics.
  <br><br>
  I'm interested in data science, especially the applications of deep learning to improve healthcare and clinical decision-making.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
