logo: "/images/logo-nghi.png" # your photo (or logo) here
title: <p align="center"> Nghi Huynh </p> # your name (or website title) here

description:
  <p align="left">
  Entry-Level Data Scientist | Chess Strategist
  </p>
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
