title: Nghi Huynh # your name (or website title) here
logo: "/images/IMG_1591.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Nghi. I'm a McGill graduate with a bachelor's in Computer Science and Biology and a minor in Mathematics. I'm interested in data science, especially the applications of deep learning in the healthcare domain.
  <br><br>
  <a href="https://www.linkedin.com/in/nghi-huynh-2b9700158/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/nghi-huynh">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
